rp_anna_posed_001: female         # a knee-length dress
rp_beatrice_posed_025: female     # a knee-length dress
rp_christine_posed_027: female    # another dress
rp_felice_posed_004: female       # long dress+tank top
rp_janett_posed_025: female
# rp_celina_posed_005: female       # a tight dress
# rp_alexandra_posed_006: female
# rp_carla_posed_006: female
# rp_cindy_posed_005: female
# rp_corey_posed_006: male
# rp_eric_posed_006: male
# rp_eric_posed_035: male
# rp_carla_posed_004: female